# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc6c3fb20daa4030befc26c36cfce906"
name = "Sync data size chart"
handle = "sync-data-product-size"
application_url = "https://unlimited-my-member-filme.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "duc-test-app.myshopify.com"

[auth]
redirect_urls = [
  "https://unlimited-my-member-filme.trycloudflare.com/auth/callback",
  "https://unlimited-my-member-filme.trycloudflare.com/auth/shopify/callback",
  "https://unlimited-my-member-filme.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
